# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'SwithBattle' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwithBattle
  pod 'Firebase/Core'

  target 'SwithBattleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'SwithBattle-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for SwithBattle-tvOS

  target 'SwithBattle-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
